### ISSUE TITLE
Unable to install using the AMQ Streams binaries

### ISSUE THREAD

**Issue by rmarting** [ansible-middleware/amq_streams#36]
##### SUMMARY

The parameters to declare the Kafka binaries are aligned with the current Kafka package artifact, however they are not valid to use with the AMQ Streams package artifact.

I tried to deploy the AMQ Streams using the binaries availables in the Red Hat Customer Portal (amq-streams-<version>-bin.zip), however the installation fails just because the output folder is not the same expected by the playbooks.

Using the following vars in a playbook:

```yaml
    # Installation offline
    #amq_streams_common_skip_download: true
    amq_streams_common_offline_install: true
    amq_streams_common_product_version: 2.4.0
    amq_streams_common_version: "{{ amq_streams_common_product_version }}"
    amq_streams_common_archive_file: "amq-streams-{{ amq_streams_common_product_version }}-bin.zip"
    amq_streams_common_download_dir: "/tmp"
``` 

The output in the final host is:

```console
[rhmw@f38mw01 opt]$ ll
total 0
drwxrwxrwx. 1 root               root        68 Apr 21 09:16 kafka_2.13-3.4.0.redhat-00006
drwxr-xr-x. 1 amq_streams_broker amq_streams  0 Jun 28 16:42 kafka_2.4.0
```

The AMQ Streams package artificat contains the binaries inside of a folder including the scala-kafka-redhat versions. That pattern does not fit with the expected in the parameters.

##### ISSUE TYPE
 - Bug Report

##### COLLECTION VERSION

```
main branch
```

##### STEPS TO REPRODUCE

Use a playbook defining the variables for the AMQ Streams binaries, something similar to:

```yaml
    # Installation offline
    #amq_streams_common_skip_download: true
    amq_streams_common_offline_install: true
    amq_streams_common_product_version: 2.4.0
    amq_streams_common_version: "{{ amq_streams_common_product_version }}"
    amq_streams_common_archive_file: "amq-streams-{{ amq_streams_common_product_version }}-bin.zip"
    amq_streams_common_download_dir: "/tmp"
```

##### EXPECTED RESULTS

Right installation using the AMQ Streams binaries

##### ACTUAL RESULTS

Different folders created not aligned with the patterns expected:

```
[rhmw@f38mw01 opt]$ ll
total 0
drwxrwxrwx. 1 root               root        68 Apr 21 09:16 kafka_2.13-3.4.0.redhat-00006
drwxr-xr-x. 1 amq_streams_broker amq_streams  0 Jun 28 16:42 kafka_2.4.0
```
