### ISSUE TITLE
Identify Zookeeper ID for each member of the assemble

### ISSUE THREAD

**Issue by rmarting** [ansible-middleware/amq_streams#7]
##### SUMMARY

The Zookeeper members include a file to identify each node inside of the assemble. This file, usually identified as, `myid` includes an unique number to identify each member of the Zookeeper assemble. The inventory should allow to identify this value for each node to allow deploy a distributed cluster.

A sample configuration could be similar to:

```yaml
---
zookeeper:
  hosts:
    node-zk-01:
      zookeeper:
        id: 1
    node-zk-02:
      zookeeper:
        id: 2
    node-zk-03:
      zookeeper:
        id: 3
```

Reference:
- https://access.redhat.com/documentation/en-us/red_hat_amq_streams/2.3/html-single/using_amq_streams_on_rhel/index#proc-running-multinode-zookeeper-cluster-str

##### ISSUE TYPE
 - Feature Idea
